import { foxPack } from "./fox/pack";

export type { ActionKey } from "./fox/actions";
export { FRAME_ASSET_REV } from "./fox/frames/frameAssetUrl";
export { frameTierResolveDebug } from "./fox/frames/tierCatalog";
export { resolveStemUrl as resolvePackStemUrl } from "./fox/actions";

/**
 * The single character pack baked into this build.
 * Generated by tools/template/init-new-pack.ps1
 */
export const activeCharacter = foxPack;
